"""Shared vocabulary. The leaf of the dependency graph: it imports nothing from app.

MAY IMPORT:  stdlib, pydantic.
IMPORTED BY: everyone.

Types live here because two or more packages speak them, not because they are "models".
Behaviour lives with the layer that owns the decision -- there is no logic in this package
beyond validation and projection.
"""

from app.domain.company import BusinessType, CompanyProfile
from app.domain.context import CallContext, CallPhase
from app.domain.models import (
    COMMITMENT_DEAD_STATES,
    DELIVERY_UNDERWAY,
    Approval,
    ApprovalKind,
    ApprovalReason,
    ApprovalStatus,
    AwardConflict,
    CallDirection,
    CallRecord,
    CallReport,
    CallStatus,
    Carrier,
    Commitment,
    CommitmentState,
    Comparison,
    ComparisonEntry,
    DecisionRow,
    DeliveryResult,
    DeliveryStatus,
    DialPlan,
    EventRow,
    IncidentSubject,
    Money,
    NotificationChannel,
    Order,
    OrderStatus,
    OutboundMessage,
    QuoteRow,
    QuoteStatus,
    Severity,
    Turn,
)
from app.domain.ports import CallPlacer, Notifier, ReportModel, Store
from app.domain.security import (
    CommitmentMode,
    CostComponent,
    CostEvidence,
    FxSnapshot,
    Mandate,
    PolicyDecision,
    PolicyOutcome,
    PreparedCommitment,
    QuoteProposal,
    ReasonCode,
)

__all__ = [
    "COMMITMENT_DEAD_STATES",
    "DELIVERY_UNDERWAY",
    "Approval",
    "ApprovalKind",
    "ApprovalReason",
    "ApprovalStatus",
    "AwardConflict",
    "BusinessType",
    "CallContext",
    "CallDirection",
    "CallPhase",
    "CallPlacer",
    "CallRecord",
    "CallReport",
    "CallStatus",
    "Carrier",
    "Commitment",
    "CommitmentMode",
    "CommitmentState",
    "CompanyProfile",
    "Comparison",
    "ComparisonEntry",
    "CostComponent",
    "CostEvidence",
    "DecisionRow",
    "DeliveryResult",
    "DeliveryStatus",
    "DialPlan",
    "EventRow",
    "FxSnapshot",
    "IncidentSubject",
    "Mandate",
    "Money",
    "NotificationChannel",
    "Notifier",
    "Order",
    "OrderStatus",
    "OutboundMessage",
    "PolicyDecision",
    "PolicyOutcome",
    "PreparedCommitment",
    "QuoteProposal",
    "QuoteRow",
    "QuoteStatus",
    "ReasonCode",
    "ReportModel",
    "Severity",
    "Store",
    "Turn",
]
